### ISSUE TITLE
How to get cam_param_opencv for my own image?

### ISSUE THREAD

**Issue by GlebPlakhtii** [SimonGiebenhain/MonoNPHM#1]
I tried to run the demo with my own image, but it requires the file 00000_cam_params_opencv.npz. How can I generate this file for my image? The preprocessing step didn't generate the camera parameters.

**Comment by SimonGiebenhain** [comment]
Hey,

Could it be that the preprocessing script crashed? 
What is inside the `metrical_tracker` folder?

**Comment by Prism-hua** [comment]
Hello, @GlebPlakhtii and @SimonGiebenhain, 

I have the similar error when running the preprocessing pipeline using `bash run.sh 00001 --no-intrinsics_provided` reconstracting from my own data.The complete output log is:
```
Traceback (most recent call last):
  File "/scratch/project/sss/MonoNPHM/src/mononphm/preprocessing/metrical-tracker/tracker.py", line 42, in <module>
    from datasets.generate_dataset import GeneratorDataset
ModuleNotFoundError: No module named 'datasets.generate_dataset'
Traceback (most recent call last):
  File "/scratch/project/sss/MonoNPHM/src/mononphm/photometric_tracking/data_loading.py", line 50, in prepare_data
    new_mica_pose = np.load(f'{env_paths.DATA_TRACKING}/{seq_name}/metrical_tracker/{seq_name}/checkpoint/{max(timestep - 1, 0):05d}_cam_params_opencv.npz') #TODO
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/project/sss/MonoNPHM/mononphm_envs/mononphm/lib64/python3.11/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/project/sss/MonoNPHM/tracking_input/CASME2/00001/metrical_tracker/00001/checkpoint/00000_cam_params_opencv.npz'
```
The folder `metrical_tracker` of my data seems not been generated. It would be so nice to receive from you! Thanks.

**Comment by SimonGiebenhain** [comment]
Hi,

It seems that there is some issue with the installation of some required packages. To be precise, the `metrical_tracker` seems to be not properly installed, as indicated by the error `ModuleNotFoundError: No module named 'datasets.generate_dataset' `.

Did you run `install_preprocessing_pipeline.sh`, as instructed in the readme? When running this script watch out for errors.

**Comment by Prism-hua** [comment]
Hi @SimonGiebenhain, thanks for your kindly assistance! Brilliant work!
I have looked into this error above. The consequence is that I solved the bug through re-installing the preprocessing pipeline and creating a `__init__.py` file under the route: `/mononphm/preprocessing/metrical-tracker/datasets` to solve `ModuleNotFoundError: No module named 'datasets.generate_dataset'`.
